### ISSUE TITLE
Add precommit-ci

### ISSUE THREAD

**Issue by roedoejet** [EveryVoiceTTS/EveryVoice#117]
To encourage/remind (😄) everyone to make sure pre-commits pass, we should use https://pre-commit.ci/ - but I think we'll have to make the repo public first

**Comment by roedoejet** [comment]
https://github.com/pre-commit/action/issues/7

**Comment by joanise** [comment]
Odd: there are way more mypy warnings on this CI run than I get locally. I get
> Found 10 errors in 4 files (checked 121 source files)
But this old run https://github.com/EveryVoiceTTS/EveryVoice/actions/runs/9700728115/job/26772805010 gets tons more than that!

**Comment by SamuelLarkin** [comment]
Is your `mypy` and friends up-to-date?
I had to update my tools.

**Comment by joanise** [comment]
I updated them yesterday as well. We should bump the minimum versions in `requirements.dev.txt` if we now depend on my recent versions than listed there.
