### ISSUE TITLE
Add prompt in `new-dataset` command to ask user to provide a speaker name for a data source

### ISSUE THREAD

**Issue by roedoejet** [EveryVoiceTTS/EveryVoice#136]
add speaker name to all utterances from a single-speaker data source

**Comment by joanise** [comment]
That's already been done I believe, and we have the `KnowSpeakerStep` question where the user can choose the ID for that one speaker. Is there anything else that's needed for this issue?

**Comment by roedoejet** [comment]
Nope, we can close this
