### ISSUE TITLE
Fix reporting in preprocessing

### ISSUE THREAD

**Issue by roedoejet** [EveryVoiceTTS/EveryVoice#342]
Currently we print the report twice because we print a partial report [here](https://github.com/roedoejet/EveryVoice/blob/d117ece5d29947e171bf181bc481c66bb26352ff/everyvoice/preprocessor/preprocessor.py#L769C21-L772C39) and then later a full report [at the end](https://github.com/roedoejet/EveryVoice/blob/d117ece5d29947e171bf181bc481c66bb26352ff/everyvoice/preprocessor/preprocessor.py#L824). We should still print the partial report related to the audio, but we should remove all non-audio related fields, and we should print it in a panel that mentions that it is a partial report.

The summary.txt should only be printed at the end.

Marc would also like to see a list of the files in the summary.txt that got skipped.

**Comment by joanise** [comment]
@roedoejet The "nans" field in the report is never even updated! What's it supposed to be for? It looks like `_iterpolate()` might have been meant to update it, or maybe `extract_pitch()`, but neither does so.
