### ISSUE TITLE
Symbol-Set step fails when the filelist contains too few utterances

### ISSUE THREAD

**Issue by MENGZHEGENG** [EveryVoiceTTS/EveryVoice#345]
If we input a filelist file with very few utterances, for example, 1 or 2, then the following error will be prompted:

`We will now present all the symbols found in your data. You will have to answer which ones are punctuation, orthographic characters, and which ones can be ignored.`
`...`
`ERROR: Symbol-Set step giving up after 20 validation failures`

It is understandable that TTS cannot work on such few utterances, but a better prompt may be helpful to remind the user of data quantity problem.

**Comment by joanise** [comment]
@MENGZHEGENG I think this problem no longer exists with the current code. Can you test again with an example that failed for you before?

**Comment by joanise** [comment]
I just tested, and even with a single utterance containing only two words, this error does not occur.
Closing this issue.
