### ISSUE TITLE
Add option to allow user to specify  filename of wav file  on synth VS using the "text" for the need

### ISSUE THREAD

**Issue by marctessier** [EveryVoiceTTS/EveryVoice#409]
It would be  really nice  and  very useful to have  an extra optional option like `--filename`     for `everyvoice synthesize from-text --text`   when you want to save a generated audio file to a very specific filename VS the "text" used  for that need.

EX:  `everyvoice synthesize from-text  --filename LJ050-0274 --text "made certain recommendations which it believes would, if adopted,"   --vocoder-path ../../MODELS/universal-2500000.ckpt logs_and_checkpoints.old/FeaturePredictionExperiment/base/checkpoints/last.ckpt`

With that example   above the generated audio file would be stored  like this right here:  `synthesis_output/wav/LJ050-0274.wav`

ESLE  the default would have been for example something like this.   `synthesis_output/wav/'made-certain-recomme-9229d5cf--default--eng--ckpt=100000--v_ckpt=5000000--pred.wav'`

**Comment by roedoejet** [comment]
please re-open if this isn't sufficient @marctessier
