### ISSUE TITLE
everyvoice synthesize from-text --filelist    ( expects a psv type  file with a header line )

### ISSUE THREAD

**Issue by marctessier** [EveryVoiceTTS/EveryVoice#433]
When trying to synth while using a "--filelist"  it expects a "psv" type  file with a header line in the format  like this file for example: `preprocessed/validation_filelist.psv`.

A few things:

1)  The "--help" for `everyvoice synthesize from-text` needs a better help message explaining what it expects as input / make more clear...  Below is what we currently see when we run "--help"

`│ --filelist        -f   FILE             Synthesize all audio in a given filelist. Use --text if you want to just synthesize one sample.`

2) Un-able to use a "plain" filelist . Where only sentences | utterences  , one per  line without a header line in the file. We get this message below that might not be clear to the end user why the synth did not work.

`/home/tes001/u/TxT2SPEECH/miniconda3_u20/envs/EveryVoice_vocoder-match/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py:104: Total length of `DataLoader` across ranks is zero. Please make sure this was your intention.`

**Comment by roedoejet** [comment]
please re-open if you still have this issue, but I have tested and this seems to work for me
