### ISSUE TITLE
Handle colon for Mohawk when using text as input

### ISSUE THREAD

**Issue by MENGZHEGENG** [EveryVoiceTTS/EveryVoice#484]
Colon is not regarded as a punctation in the text of `Mohawk`
We may need to handle this carefully in the pre-processing process

**Comment by roedoejet** [comment]
I will work on this. In the last meeting we agreed to do the following:

- in the wizard remove all characters that are punctuation already
- ask the user to inspect the shared text config file and move any punctuation characters over to the characters set
- create a model validator to make sure there are no characters that are in both punctuation and not-punctuation.
