### ISSUE TITLE
tilde is not resolved properly when checking wavs folder

### ISSUE THREAD

**Issue by roedoejet** [EveryVoiceTTS/EveryVoice#539]
See below:

![image](https://github.com/user-attachments/assets/821aadcb-b101-411f-9482-0dbda8360bdf)

**Comment by joanise** [comment]
`~` is a shell expansion thing, I would expect it to work nowhere at all, except on the bash command line.

Ah, but `questionary.path` autocompletes assuming it'll get interpreted, but doesn't then do the substitution, I see the problem. The string that gets returned is one `questionary.path` suggests will work, but then it doens't. That's true for all questions using path, and it's it's true if you use `~username`.

I can take this one.

**Comment by joanise** [comment]
Solution: call `os.path.expanduser(path)` on the path returned by `questionary.path`, or else `Path.expanduser()` if it's a `pathlib.Path` object already.
