### ISSUE TITLE
An input breaks the preprocess pipeline

### ISSUE THREAD

**Issue by MENGZHEGENG** [EveryVoiceTTS/EveryVoice#540]
The input is:
`kaieshónhtshera'/kasteristáhtshera'` which is in our dataset

Which will lead to
`everyvoice.exceptions.OutOfVocabularySymbolError: Sequence ['k', 'a', 'i', 'e', 's', 'h', 'ó', 'n', 'h', 't', 's', 'h', 'e', 'r', 'a', "'", '', '', 'k', 'a', 's', 't',
'e', 'r', 'i', 's', 't', 'á', 'h', 't', 's', 'h', 'e', 'r', 'a', "'", ' ', 't', 'ó', 'k', 'a', "'", ' ', 'n', 'ò', 'n', ':', 'w', 'a', ' ', 'e', 'n', 'w', 'á', 'h', 's',
'e', 'h', 't', 'e', "'", ' ', 'n', 'e', ' ', 'k', 'a', "'", 'n', 'i', 'k', 'o', 'n', 'h', 'r', 'a', 'k', 's', 'é', 'n', 'h', 't', 's', 'h', 'e', 'r', 'a', "'", '.']
contains item`

**Comment by MENGZHEGENG** [comment]
Another input is `waharístenhte'/wahatsíhkwenhte`

**Comment by roedoejet** [comment]
yes, thanks for raising Tim. this is related to this issue: https://github.com/EveryVoiceTTS/EveryVoice/issues/460 so I will close this in favour of that issue.
