### ISSUE TITLE
remove vocoder requirement for spec synthesis

### ISSUE THREAD

**Issue by MENGZHEGENG** [EveryVoiceTTS/EveryVoice#542]
Currently, for vocoder matching,  when generated the synthesized mel spectrogram, we need to path a model for vocoder, or it will report an error.

To this end, it may help if the relevant documentation at https://docs.everyvoice.ca/stable/guides/finetune/ can be updated. 

Thanks!

**Comment by roedoejet** [comment]
this is actually a bug - I don't see any reason why we should need a vocoder path just to generate mel spectrograms

**Comment by roedoejet** [comment]
fixed in https://github.com/EveryVoiceTTS/EveryVoice/pull/551
