### ISSUE TITLE
Add versioning information to all model files

### ISSUE THREAD

**Issue by joanise** [EveryVoiceTTS/EveryVoice#559]
### Description & Motivation

Vocoder Checkpoints, Feature Prediction checkpoints, etc, need to have versioning information, for two purposes:
 - simplify error messages when the wrong type of model gets loaded
 - recognize that a file is in the format of an older version, and support converting it on the fly if possible or giving good error messages if not.

### Pitch

Just like `.readalong` files now have file format version numbers, we really need this for EV models too.

**Comment by SamuelLarkin** [comment]
Done by:
https://github.com/EveryVoiceTTS/EveryVoice/pull/565
https://github.com/EveryVoiceTTS/FastSpeech2_lightning/pull/92
https://github.com/EveryVoiceTTS/HiFiGAN_iSTFT_lightning/pull/38
https://github.com/EveryVoiceTTS/DeepForcedAligner/pull/28
