### ISSUE TITLE
Multiple issues with the configuration wizard

### ISSUE THREAD

**Issue by roedoejet** [EveryVoiceTTS/EveryVoice#7]
A big refactor of the configuration wizard took place in https://github.com/roedoejet/EveryVoice/pull/5 but there are still several known Issues:

- [x] The terminal menu I am using doesn't give an option to continue without selecting. This means for some steps (like the symbol selection step) you are forced to make a choice, when simply no selection is actually valid.

- [x] The terminal menu formatting is such that it fills the whole screen and doesn't show the preceding instructions, so the user needs to scroll up to see the instructions, which is confusing.
- [x] Only basic unit tests exist. I would like to discuss what adequate testing would look like here, either more e2e type testing by simulating typical paths through the TUI, or by just unit testing the prompts, validations, and effects of individual steps. This is open for discussion
- [x] It would be nice if there was better integration with g2p around symbol sets
the yellow colour of the prompt responses is ghastly and should be changed
- [ ] there is no "back button" if you make a mistake
- [ ] if you exit out of the config wizard, there is no way to save your progress. It might be nice to think about how to do something like that. I.e. some sort of declarative syntax for how questions would get answered that could double as a progress saver and as a testing aide.
- [x] missing data permissions declaration step

**Comment by joanise** [comment]
Moving the back button and saving progress to #545

**Comment by joanise** [comment]
And closing what's left here as having been completed in alpha.
